Traceback (most recent call last):                                           
  File "/gpfs/home/uqz9095/OMT-SAM/train_one_gpu.py", line 484, in <module>
    main()
    ~~~~^^
  File "/gpfs/home/uqz9095/OMT-SAM/train_one_gpu.py", line 387, in main
    wandb.log({"epoch_loss": epoch_loss}, {"epoch_dice": epoch_dice})
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 449, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 436, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1982, in log
    self._log(data=data, step=step, commit=commit)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1705, in _log
    self._partial_history_callback(data, step, commit)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 391, in wrapper
    return func(self, *args, **kwargs)
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/wandb_run.py", line 1532, in _partial_history_callback
    self._backend.interface.publish_partial_history(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self,
        ^^^^^
    ...<4 lines>...
        publish_step=not_using_tensorboard,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/uqz9095/miniconda3/lib/python3.13/site-packages/wandb/sdk/interface/interface.py", line 698, in publish_partial_history
    partial_history.step.num = step
    ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'dict' object cannot be interpreted as an integer
